"""Word document report generator."""

from pathlib import Path
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from config.settings import Settings
from src.llm.state import ReportState
from src.utils.logger import app_logger


class WordGenerator:
    """Generates Word format reports."""

    def __init__(self, settings: Settings, state: ReportState):
        """Initialize Word generator.

        Args:
            settings: Application settings.
            state: LangGraph workflow state.
        """
        self.settings = settings
        self.state = state
        self.logger = app_logger

    def generate(self) -> str:
        """Generate Word report.

        Returns:
            Path to generated Word file.
        """
        self.logger.info("Generating Word report")

        doc = Document()

        # Set document properties
        doc.core_properties.title = self.settings.report.company_name
        doc.core_properties.author = self.settings.report.author
        doc.core_properties.comments = "Generated by BMW Sales Analysis System"

        # Build content
        self._build_content(doc)

        # Save document
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"bmw_sales_report_{timestamp}.docx"
        output_path = self.settings.report.output_dir / filename
        output_path.parent.mkdir(parents=True, exist_ok=True)

        doc.save(str(output_path))

        self.logger.info(f"Word report saved: {output_path}")

        return str(output_path)

    def _build_content(self, doc: Document) -> None:
        """Build Word document content.

        Args:
            doc: Python-docx Document object.
        """
        # Title
        title = doc.add_heading(self.settings.report.company_name, 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Metadata
        meta_para = doc.add_paragraph()
        meta_para.add_run(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}").bold = True
        doc.add_paragraph(f"Author: {self.settings.report.author}")

        doc.add_page_break()

        # Executive Summary
        if self.state.get("executive_summary"):
            doc.add_heading("Executive Summary", level=1)
            doc.add_paragraph(self.state["executive_summary"])

        # Analysis Sections
        if self.state.get("analysis_sections"):
            sections = self.state["analysis_sections"]

            if "sales_trends" in sections:
                doc.add_heading("Sales Performance Trends", level=1)
                doc.add_paragraph(sections["sales_trends"])

            if "regional_analysis" in sections:
                doc.add_heading("Regional Analysis", level=1)
                doc.add_paragraph(sections["regional_analysis"])

            if "product_performance" in sections:
                doc.add_heading("Product Performance", level=1)
                doc.add_paragraph(sections["product_performance"])

        # Visualizations
        if self.state.get("plot_paths"):
            doc.add_heading("Visualizations", level=1)
            for plot_path in self.state["plot_paths"]:
                if Path(plot_path).exists():
                    try:
                        doc.add_picture(plot_path, width=Inches(6))
                        doc.add_paragraph()
                    except Exception as e:
                        self.logger.warning(f"Could not add image {plot_path}: {e}")

        # Recommendations
        if self.state.get("recommendations"):
            doc.add_heading("Recommendations", level=1)
            for rec in self.state["recommendations"]:
                para = doc.add_paragraph(rec, style="List Bullet")

